version: '0.13.{build}'

init:
- git config --global core.autocrlf true

build_script:
- ps: .\build.ps1

test: off

cache:
- tools -> build.cake
- tools -> build.ps1

artifacts:
- path: nupkgs\*.nupkg
  name: NuPkgs